name: rate-my-rest
services:
  - name: backend
    source_dir: /backend
    github:
      branch: main
      deploy_on_push: true
    run_command: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    build_command: pip install -r requirements.txt && alembic upgrade head
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
        preserve_path_prefix: true
    health_check:
      http_path: /health
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: GOOGLE_PLACES_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: ENVIRONMENT
        scope: RUN_AND_BUILD_TIME
        value: "production"
      - key: REDIS_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET

  - name: frontend
    source_dir: /frontend
    github:
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: REACT_APP_API_URL
        scope: BUILD_TIME
        value: "${backend.PUBLIC_URL}/api"
      - key: REACT_APP_ENVIRONMENT
        scope: BUILD_TIME
        value: "production"

databases:
  - name: rate-my-rest-db
    engine: PG
    num_nodes: 1
    size: basic-xs
    version: "14"