"""Add lottery system models

Revision ID: 11d8068a0a6a
Revises: 
Create Date: 2025-09-25 12:50:52.257706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d8068a0a6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_lotteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=True),
    sa.Column('prize_amount', sa.Float(), nullable=True),
    sa.Column('prize_currency', sa.String(length=3), nullable=True),
    sa.Column('winner_user_id', sa.Integer(), nullable=True),
    sa.Column('winning_ticket_number', sa.Integer(), nullable=True),
    sa.Column('total_tickets', sa.Integer(), nullable=True),
    sa.Column('is_drawn', sa.Boolean(), nullable=True),
    sa.Column('draw_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['winner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_lotteries_id'), 'monthly_lotteries', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_lotteries_month'), 'monthly_lotteries', ['month'], unique=True)
    op.create_table('user_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('monthly_points', sa.Integer(), nullable=True),
    sa.Column('current_month', sa.String(length=7), nullable=True),
    sa.Column('total_ratings', sa.Integer(), nullable=True),
    sa.Column('total_photos', sa.Integer(), nullable=True),
    sa.Column('total_checkins', sa.Integer(), nullable=True),
    sa.Column('bulk_import_points', sa.Integer(), nullable=True),
    sa.Column('bulk_import_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_points_current_month'), 'user_points', ['current_month'], unique=False)
    op.create_index(op.f('ix_user_points_id'), 'user_points', ['id'], unique=False)
    op.create_index(op.f('ix_user_points_total_points'), 'user_points', ['total_points'], unique=False)
    op.create_index(op.f('ix_user_points_user_id'), 'user_points', ['user_id'], unique=False)
    op.create_table('restaurant_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('check_in_lat', sa.Float(), nullable=False),
    sa.Column('check_in_lng', sa.Float(), nullable=False),
    sa.Column('distance_from_restaurant', sa.Float(), nullable=True),
    sa.Column('check_in_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('min_stay_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'RATED', 'EXPIRED', name='checkinstatus'), nullable=True),
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rating_id'], ['ratings.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_checkins_id'), 'restaurant_checkins', ['id'], unique=False)
    op.create_index(op.f('ix_restaurant_checkins_restaurant_id'), 'restaurant_checkins', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_restaurant_checkins_status'), 'restaurant_checkins', ['status'], unique=False)
    op.create_index(op.f('ix_restaurant_checkins_user_id'), 'restaurant_checkins', ['user_id'], unique=False)
    op.create_table('detailed_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('checkin_id', sa.Integer(), nullable=True),
    sa.Column('overall_rating', sa.Float(), nullable=False),
    sa.Column('food_quality_expectation', sa.Integer(), nullable=True),
    sa.Column('portion_size_appropriate', sa.Integer(), nullable=True),
    sa.Column('food_fresh_prepared', sa.Integer(), nullable=True),
    sa.Column('service_attentive', sa.Integer(), nullable=True),
    sa.Column('wait_times_reasonable', sa.Integer(), nullable=True),
    sa.Column('atmosphere_pleasant', sa.Integer(), nullable=True),
    sa.Column('restaurant_clean', sa.Integer(), nullable=True),
    sa.Column('noise_level_appropriate', sa.Integer(), nullable=True),
    sa.Column('restaurant_welcoming', sa.Integer(), nullable=True),
    sa.Column('prices_fair', sa.Integer(), nullable=True),
    sa.Column('would_recommend', sa.Integer(), nullable=True),
    sa.Column('would_return', sa.Integer(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('has_photos', sa.Boolean(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['checkin_id'], ['restaurant_checkins.id'], ),
    sa.ForeignKeyConstraint(['rating_id'], ['ratings.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detailed_ratings_id'), 'detailed_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_detailed_ratings_rating_id'), 'detailed_ratings', ['rating_id'], unique=False)
    op.create_index(op.f('ix_detailed_ratings_restaurant_id'), 'detailed_ratings', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_detailed_ratings_user_id'), 'detailed_ratings', ['user_id'], unique=False)
    op.create_table('point_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.Column('checkin_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['checkin_id'], ['restaurant_checkins.id'], ),
    sa.ForeignKeyConstraint(['rating_id'], ['ratings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_transactions_id'), 'point_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_point_transactions_month'), 'point_transactions', ['month'], unique=False)
    op.create_index(op.f('ix_point_transactions_user_id'), 'point_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_point_transactions_user_id'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_month'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_id'), table_name='point_transactions')
    op.drop_table('point_transactions')
    op.drop_index(op.f('ix_detailed_ratings_user_id'), table_name='detailed_ratings')
    op.drop_index(op.f('ix_detailed_ratings_restaurant_id'), table_name='detailed_ratings')
    op.drop_index(op.f('ix_detailed_ratings_rating_id'), table_name='detailed_ratings')
    op.drop_index(op.f('ix_detailed_ratings_id'), table_name='detailed_ratings')
    op.drop_table('detailed_ratings')
    op.drop_index(op.f('ix_restaurant_checkins_user_id'), table_name='restaurant_checkins')
    op.drop_index(op.f('ix_restaurant_checkins_status'), table_name='restaurant_checkins')
    op.drop_index(op.f('ix_restaurant_checkins_restaurant_id'), table_name='restaurant_checkins')
    op.drop_index(op.f('ix_restaurant_checkins_id'), table_name='restaurant_checkins')
    op.drop_table('restaurant_checkins')
    op.drop_index(op.f('ix_user_points_user_id'), table_name='user_points')
    op.drop_index(op.f('ix_user_points_total_points'), table_name='user_points')
    op.drop_index(op.f('ix_user_points_id'), table_name='user_points')
    op.drop_index(op.f('ix_user_points_current_month'), table_name='user_points')
    op.drop_table('user_points')
    op.drop_index(op.f('ix_monthly_lotteries_month'), table_name='monthly_lotteries')
    op.drop_index(op.f('ix_monthly_lotteries_id'), table_name='monthly_lotteries')
    op.drop_table('monthly_lotteries')
    # ### end Alembic commands ###